Updated location of schxslt default

diff --git a/bin/batch-schematron b/bin/batch-schematron
--- a/bin/batch-schematron
+++ b/bin/batch-schematron
@@ -1,16 +1,26 @@
 #!/bin/bash
 PROJECT=`cd $1; pwd`
 ROOT=`cd $(dirname $(realpath -s $0))/..; pwd`
-SCHXSLT_DEFAULT=$ROOT/lib/schxslt/xslt/2.0/pipeline-for-svrl.xsl
+SCHXSLT_DEFAULT=$ROOT/lib/schxslt/2.0/pipeline-for-svrl.xsl
 
 if test -z "$SCHXSLT"; then
     echo "Warning: SCHXLT not set, using default: ${SCHXSLT_DEFAULT}"
     SCHXSLT="${SCHXSLT_DEFAULT}"
 fi
 
+if test -z $SCHEMA; then
+    echo "Error: SCHEMA not set"
+    exit 1
+fi
+
+if test -z $PROJECT; then
+    echo "Error: PROJECT not set"
+    exit 1
+fi
+
 bin/saxon \
-    -xsl:$ROOT/schemas/xslt/batch-schematron-validate.xslt \
+    -xsl:$ROOT/xslt/batch-schematron-validate.xslt \
     -s:$SCHEMA \
     sources-base-dir-uri=file:$PROJECT/target \
-	reports-base-dir-uri=file:$PROJECT/report \
-    schxslt:$SCHXSLT
+    reports-base-dir-uri=file:$PROJECT/report \
+    schxslt-uri=file:$SCHXSLT
