Updated EOL

diff --git a/bin/xspec b/bin/xspec
--- a/bin/xspec
+++ b/bin/xspec
@@ -1,21 +1,24 @@
 #!/bin/bash
+SCRIPT_DIR=`dirname ${BASH_SOURCE[0]-$0}`
 
-set -e
-for xspec in $( find $1 -type f -name '*.xspec' ); do
-  echo "################################################"
-  printf "\n"
-  echo "TEST $(basename -- $xspec)"
-  printf "\n"
-  /bin/bash $XSPEC_HOME/bin/xspec.sh -e -t $xspec || exitcode=$?
-  printf "\n\n"
-done
+XSPEC_HOME=`readlink -f "${SCRIPT_DIR}/../lib/xspec-2.2.4"`
 
-echo "################################################"
-printf "\n"
-if [ "$exitcode" == "0" ]; then
-    echo "Result: SUCCES"
-else
-    echo "Result: FAILED"
+SAXON_HOME_DEFAULT=`readlink -f "${SCRIPT_DIR}/../lib/saxon"`
+
+if test -z "$SAXON_HOME"; then
+    echo "Warning: SAXON_HOME not set, using default: ${SAXON_HOME_DEFAULT}"
+    SAXON_HOME="${SAXON_HOME_DEFAULT}"
 fi
 
-exit $exitcode
+for f in \
+    "${SAXON_HOME}"/saxon9?e.jar \
+    "${SAXON_HOME}"/[Ss]axon-?[eE]-?*.?*.jar; do
+    [ -f "${f}" ] && SAXON_CP="${f}"
+done
+
+if test -z "$SAXON_CP"; then
+    echo "Error: Saxon jar not found in ${SAXON_HOME}"
+    exit 1
+fi
+
+$XSPEC_HOME/bin/xspec.sh -cp "${SAXON_CP}" "$@"
